name: Attendance Bot
on:
  schedule:
    # 10:05 AM CST is 16:05 UTC. 
    # The '1,3' represents Monday and Wednesday
    - cron: '05 16 * * 1,3'
  workflow_dispatch: 

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install playwright
          playwright install --with-deps chromium # Installs Linux system libraries

      - name: Run Script
        env:
          GOOGLE_COOKIES: ${{ secrets.GOOGLE_COOKIES }} # Bridges secret to Python code
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: python bot.py

      - name: Upload Debug Screenshots
        if: always() # Uploads even if the script fails so you can debug
        uses: actions/upload-artifact@v4
        with:
          name: debug-screenshots
          path: "*.png"
